language: node_js
node_js: 7
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    addons:
      apt:
        packages:
          - rpm
          - g++-4.8
          - icnsutils
          - graphicsmagick
          - xz-utils
          - xorriso
          - g++-multilib
          - libxss-dev:i386
  - os: osx
    osx_image: xcode8.3

install:
  #- export CXX="g++-4.8"
  - yarn
  - cd app && yarn && cd ..
  #- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 3

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export CSC_IDENTITY_AUTO_DISCOVERY=false; fi
  - node --version
  #- yarn lint
  - yarn release -- --x64 --ia32
  #- yarn test
  #- yarn test-e2e

branches:
  only:
    - master
    - develop
    - react

notifications:
  email:
    on_success: never
    on_failure: change
