# build: off

image: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master
    - develop

skip_tags: true

environment:
  nodejs_version: "7"

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - yarn

test_script:
  - node --version
  - yarn --version
  # - yarn test
  # - yarn e2e

build_script:
  - yarn release -- --win appx

artifacts:
  - path: 'dist\**\*.exe'
  - path: 'dist\**\*.appx'
