os: unstable

platform:
  - x64

environment:
  nodejs_version: 7

skip_tags: true

#cache:
#  - "%LOCALAPPDATA%/Yarn"
#  - node_modules -> package.json
#  - app/node_modules -> app/package.json

branches:
  only:
    - master
    - develop
    - react

matrix:
  fast_finish: true

#build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - yarn
  - cd app && yarn

test_script:
  - node --version
  #- yarn lint
  #- yarn test
  #- yarn test-e2e

build_script:
  - yarn release -- --ia32 --x64

artifacts:
  - path: 'release\**\*.exe'
